language: php

# faster builds on new travis setup not using sudo
sudo: false

php:
  - 7.1
install:
  - travis_retry composer install --no-interaction

script:
  - composer why GuzzleHttp/guzzle
  - vendor/bin/codecept run
