language: php

# faster builds on new travis setup not using sudo
sudo: false

php:
  - 7.2
before_script:
  # disable xdebug to speed up tests
  - phpenv config-rm xdebug.ini
install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer install --prefer-dist --no-interaction

script:
  - vendor/bin/codecept run
