language: php
dist: trusty
php:
    - 7.2
before_script:
    # disable xdebug to speed up tests
    - phpenv config-rm xdebug.ini

script:
    - composer create-project yiisoft/yii2-app-basic myTestApp
    - composer install
    - vendor/bin/codecept run
