resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource

resources:
- name: helpers
  type: git
  source:
    uri: https://github.com/TonisOrmisson/yii2-helpers.git

- name: notify
  type: slack-notification
  source:
    url: https://hooks.slack.com/services/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

jobs:
- name: run-tests
  public: true
  plan:
  - get: helpers
    trigger: true
  - task: run tests
    on_failure:
      put: notify
      params:
        attachments: '[{"color": "danger","text": "Build $BUILD_NAME for Yii2-Helpers failed!"}]'
    on_abort:
      put: notify
      params:
        attachments: '[{"color": "warning","text": "Build $BUILD_NAME for Yii2-Helpers was aborted!"}]'
    on_success:
      put: notify
      params:
        attachments: '[{"color": "good","text": "Build $BUILD_NAME for Yii2-Helpers was successful!"}]'
    privileged: true
    config:
      inputs:
      - name: helpers
      platform: linux
      caches:
        - path: ../../../root/.composer/cache
      image_resource:
        type: docker-image
        source:
          repository: tonisormisson/dev-lemp

      run:
        path: sh
        args:
        - -exc
        - |
          cd helpers
          composer install --no-interaction
          vendor/bin/codecept run --coverage --coverage-xml

