resources:
- name: helpers
  type: git
  source:
    uri: https://github.com/TonisOrmisson/yii2-helpers.git

jobs:
- name: run-tests
  public: true
  plan:
  - get: helpers
    trigger: true
  - task: run tests
    privileged: true
    config:
      inputs:
      - name: helpers
      platform: linux
      caches:
        - path: ../../../root/.composer/cache
      image_resource:
        type: docker-image
        source:
          repository: tonisormisson/dev-lemp

      run:
        path: sh
        args:
        - -exc
        - |
          cd helpers
          composer install --no-interaction
          vendor/bin/codecept run --coverage --coverage-xml

